apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend
spec:
  selector:
    {{- include "temperature.selectorLabels" . | nindent 4 }}
    component: backend
  ports:
    - protocol: TCP
      port: {{ .Values.service.backendPort }}
      targetPort: {{ .Values.backend.port }}
  type: {{ .Values.service.type }}